name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        PUBLIC_URL=https://chrastillab.github.io/Concord/branch-${{ github.ref_name }} npm run build
      env:
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
        REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}

    - name: Remove old files
      run: |
        rm -rf ./branch-${{ github.ref_name }}/*
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        if [ -z "$(git status --porcelain)" ]; then
        echo "No changes to commit."
        else
        git commit -am "Remove outdated files"
        fi

    - name: Copy new build to directory
      run: |
        mkdir -p ./branch-${{ github.ref_name }}
        cp -r ./build/* ./branch-${{ github.ref_name }}

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Deploy updates"
        git push
